### ISSUE TITLE
does not work with line break

### ISSUE THREAD

**Issue by gunnarbittersmann** [LeaVerou/conic-gradient#11]
The polyfill not work with a line break after the opening (

This fails:
conic-gradient(
        at center,
        red 45deg, white 45deg, white 135deg, red 135deg, red 225deg, white 225deg, white 315deg, red 315deg

However, other line breaks inside work:
conic-gradient(at center,
        red 45deg, white 45deg, white 135deg, red 135deg, red 225deg, white 225deg, white 315deg, red 315deg

**Comment by LeaVerou** [comment]
Fixed, thanks!
