### ISSUE TITLE
Displays wrongly in Safari

### ISSUE THREAD

**Issue by Haroenv** [LeaVerou/conic-gradient#2]
![](https://i.imgur.com/5omIBeU.png)

**Comment by greystate** [comment]
The code samples seem to render OK after 1f13c06 - seems to have been caused by _-prefix-free_ not kicking in.

Gradients still don't display even though they're generated and the SVG is present in the DOM...

**Comment by LeaVerou** [comment]
Yup, it’s in my "to look into asap" list. Thanks for reporting!

**Comment by greystate** [comment]
FWIW, gradients work in WebKit version r185802

**Comment by LeaVerou** [comment]
FWIW, the root of the issue is that this doesn’t work: http://dabblet.com/gist/0d5018f6c81484458472

**Comment by simsketch** [comment]
Looks like that dabblet is working in Safari as of at least version 9.0 (11601.1.56)

Works for me.

**Comment by zykadelic** [comment]
+1 working in Safari 9.0

**Comment by Haroenv** [comment]
Yep, but not in lower.

**Comment by LeaVerou** [comment]
Woohoo!! Closing this then!
