### ISSUE TITLE
Control gradient angle with JavaScript

### ISSUE THREAD

**Issue by edwinbradford** [LeaVerou/conic-gradient#27]
I'm making a very simple international pie chart clock, is it possible to control the angle of the colour with JavaScript? I'm currently using CSS variables and it works in Chrome with Experimental Web Platform Features enabled but doesn't work when they're turned off.

Here's the JSFiddle https://jsfiddle.net/edwinbradford/vz5z5gpc/

**Comment by LeaVerou** [comment]
Unfortunately this polyfill doesn't support CSS variables :(
It could be made to support it though, if you're interested in working on that and sending a pull request, I can provide some guidance on how to do it.

**Comment by edwinbradford** [comment]
Sorry, my fault, I realised it's already stated in your documentation. Sadly it's beyond my time and ability to implement CSS variables but I thoroughly enjoyed experimenting with Conic gradients anyway so thanks for the great tool. I have another API that does what I need for now and I can always come back to conic gradients at another date.
