### ISSUE TITLE
Currently not able to use the polyfill to use in Firefox - Doesn't Render

### ISSUE THREAD

**Issue by elmiguel** [LeaVerou/conic-gradient#29]
A colleague and I are trying to use your polyfill to demonstrate a small pie chart based off your talk on Even More CSS Secrets. We created a small codepen project and did the basic setup. 

https://codepen.io/irscdev/pen/gdqQNd

If you view this in Chrome, everything work fine. Yet, if you use Firefox, this does not render. I am currently using FF62. 

The interesting part of this, is that it works on your github.io page and other places but not our codepen project nor localhost.

**Comment by LeaVerou** [comment]
I suspect that including Prefixfree via the checkbox in the CSS section does not guarantee it runs before the conic gradient polyfill. Try including it explicitly, in the JS settings?

**Comment by elmiguel** [comment]
Removed the prefix settings in the CSS settings and only the polyfill is loaded via the JS settings. No effect. It stills does not render in FF.

**Comment by elmiguel** [comment]
I have also edited it to use the polyfill directly in the JS editor and the same issue occurs.

**Comment by LeaVerou** [comment]
No, it needs PrefixFree to run. I told you to try loading PrefixFree directly, before the polyfill, not to get rid of it altogether.

**Comment by elmiguel** [comment]
Ok, forgive me if I am mistaken on what you mean by running PrefixFree directly. I have copied the source from your repo and pasted in the JS editor and the pointed to the conic js via the codepen settings. No effect, the issue is still the same. I have also tried running the PrefixFree code in the editor first then pasting the conic polyfill immediately after that. Still to no avail. 

I have copied the links to both repos (github.io pages; https protocols) and made sure that I included the PrefixFree first. No results. I know the order is correct as if I load the polyfill first, in FF, the pie doesn't render. 

As it stands now, PrefixFree loads first then the polyfill and it doesn't render but only a black circle. When you view the codepen project, do you see the black circle? 

-Edit: I have also npm'd both repo and added them script tags on a test html page. I added the code from codepen into their respective slots and the issue is still the same: Firefox just renders a black circle as Chrome renders fine. Safari doesn't render at all.

-Edit: Here is my github repo of the current example: https://github.com/elmiguel/conic-gradient-example, thought that you could see if this reproduces the issue as of late.

**Comment by LeaVerou** [comment]
Oh, I see! You're using CSS variables. Sadly, the polyfill doesn’t support that :(

**Comment by elmiguel** [comment]
Ok, interesting, in your talk you used custom css variables. Did you use a custom app?

[https://www.youtube.com/watch?v=vs34f9FiHps&t=3764s](url)

**Comment by LeaVerou** [comment]
No, I used Chrome, which supports `conic-gradient()` natively.

**Comment by elmiguel** [comment]
OK, for now we just created some classes by increments of 10 and pre-calc the amounts to inject into the classes on the view. Thank you for your assistants.
