### ISSUE TITLE
Alpha gradient introduces grayness

### ISSUE THREAD

**Issue by Ken-g6** [LeaVerou/conic-gradient#3]
Test: `background: conic-gradient(rgba(43,247,254,0), rgba(43,247,254,1));`

Expected result: A smooth conic gradient from the background color (white on your conic gradient page) to increasingly less-light-blue to light-blue.  Try replacing conic-gradient with linear-gradient for an example of the correct colors.

Actual result: A conic gradient from the background color (white on your conic gradient page) to gray to grayish-blue to light blue.

![alpha-gradient](https://cloud.githubusercontent.com/assets/281895/8270010/16058424-1784-11e5-8ed8-2935a29618a4.png)

Browser: Firefox 39 beta in Linux

**Comment by LeaVerou** [comment]
Thanks for reporting! Interestingly, this doesn't occur in Chrome (both the color problem and the moire pattern).

**Comment by tabatkins** [comment]
I'll bet this is caused by feeding the color through the browser for parsing, and the browser normalizing a fully-transparent color to `rgba(0,0,0,0)` (transparent black).  Lea, are you using the "paint into a 1 pixel canvas, then read the color out" trick you've used elsewhere?

**Comment by Ken-g6** [comment]
This is working correctly now in Firefox 40.  Thanks!
